const AURORA_DEFAULT_DATA = {
  "version": 3,
  "settings": {
    "name": "Aurora Confeitaria Artesanal",
    "tagline": "Feito com amor",
    "logo": "",
    "banner": "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
    "sobreImage": "products/4c3b51e1-88fc-473a-a06d-e3f13e31c525.jpg",
    "whatsapp": "5535987216486",
    "instagram": "https://www.instagram.com/a.aurora.confeitaria",
    "instagramUser": "@a.aurora.confeitaria",
    "facebook": "",
    "email": "contato@aurora.com",
    "address": "Rua dos Expedicionários, 237, Boa Esperança MG, 37170-000, Brasil",
    "hours": "Pedidos pelo WhatsApp",
    "followers": "",
    "posts": "",
    "mapEmbed": "",
    "heroBadge": "Confeitaria artesanal · Boa Esperança/MG",
    "heroStory": [],
    "sobreText1": "A Aurora Confeitaria nasceu do sonho de transformar momentos simples em lembranças especiais. Cada receita é preparada artesanalmente, com ingredientes selecionados, muito carinho e a dedicação de quem acredita que um doce pode tornar o dia de alguém mais feliz.",
    "sobreText2": "Mais do que vender sobremesas, queremos criar experiências. Também acreditamos em fazer a diferença onde estamos — compartilhar o bem faz parte da nossa essência. Seja bem-vindo à Aurora Confeitaria."
  },
  "auth": {
    "email": "admin@aurora.com",
    "password": "aurora123"
  },
  "categories": [
    {
      "id": "cat-copos",
      "name": "Copos Brownie",
      "slug": "copos"
    },
    {
      "id": "cat-sandu",
      "name": "Sandubrownies",
      "slug": "sandubrownies"
    },
    {
      "id": "cat-cookies",
      "name": "Cookies",
      "slug": "cookies"
    },
    {
      "id": "cat-potes",
      "name": "Potes",
      "slug": "potes"
    },
    {
      "id": "cat-bolos",
      "name": "Bolos",
      "slug": "bolos"
    },
    {
      "id": "cat-especiais",
      "name": "Especiais",
      "slug": "especiais"
    }
  ],
  "products": [
    {
      "id": "p0",
      "name": "Copo da Felicidade",
      "description": "Copo 300ml com camadas generosas — escolha o sabor e peça pelo WhatsApp.",
      "price": 29,
      "categoryId": "cat-copos",
      "image": "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
      "featured": true,
      "slug": "copo-da-felicidade",
      "size": "300ml",
      "flavors": [
        "Ninho com Nutella",
        "Ninho com Morangos",
        "Ferrero",
        "Kinder",
        "Brigadeiro com Morangos",
        "Brigadeiro com Ninho e Nutella",
        "Maracujá com Brigadeiro"
      ],
      "promoActive": true,
      "promoPrice": 22,
      "promoLabel": "Promoção",
      "active": true
    },
    {
      "id": "p1",
      "name": "Copo Brownie Clássico",
      "description": "Camadas de brownie, creme de chocolate e creme baunilha no potinho — o clássico da casa.",
      "price": 0,
      "categoryId": "cat-copos",
      "image": "products/06b9382c-b7eb-422d-bd3a-e7b46b44a936.jpg",
      "featured": true,
      "slug": "copo-brownie-classico",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p2",
      "name": "Cookies Artesanais",
      "description": "Cookies grossos no estilo americano: chocolate clássico e red velvet com recheio cremoso.",
      "price": 0,
      "categoryId": "cat-cookies",
      "image": "products/0ff19f98-37de-4629-9520-af19c38f27cc.jpg",
      "featured": true,
      "slug": "cookies-artesanais",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p3",
      "name": "Sandubrownie Kinder",
      "description": "Sanduíche de brownie com creme branco e recheio Kinder — embalagem feita com amor.",
      "price": 0,
      "categoryId": "cat-sandu",
      "image": "products/27cca0b6-2fd5-4d60-8c72-92a1e8097364.jpg",
      "featured": true,
      "slug": "sandubrownie-kinder",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p4",
      "name": "Cookie Recheado de Chocolate",
      "description": "Cookie artesanal aberto na hora, com recheio de chocolate derretido e textura crocante.",
      "price": 0,
      "categoryId": "cat-cookies",
      "image": "products/4ba1b56d-f4ea-4b7d-9c2d-2f8fbeab8bb1.jpg",
      "featured": true,
      "slug": "cookie-recheado-chocolate",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p5",
      "name": "Sandubrownie de Morango",
      "description": "Duas camadas de brownie com creme, ganache e morangos frescos — generoso e irresistível.",
      "price": 0,
      "categoryId": "cat-sandu",
      "image": "products/4c3b51e1-88fc-473a-a06d-e3f13e31c525.jpg",
      "featured": true,
      "slug": "sandubrownie-morango",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p6",
      "name": "Brownie no Pote com Morango",
      "description": "Base de brownie, creme suave e calda de morango fresco na marmitinha.",
      "price": 0,
      "categoryId": "cat-potes",
      "image": "products/679de717-08f0-4c2d-a601-7bb8bae07bc4.jpg",
      "featured": false,
      "slug": "brownie-pote-morango",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p7",
      "name": "Copo Morango, Creme e Chocolate",
      "description": "Camadas de morango, creme amanteigado e ganache de chocolate no potinho transparente.",
      "price": 0,
      "categoryId": "cat-copos",
      "image": "products/6aceecd0-e407-4478-b511-f03af2e22e65.jpg",
      "featured": true,
      "slug": "copo-morango-creme-chocolate",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p8",
      "name": "Pizza Brownie",
      "description": "Brownie em formato pizza com cremes, frutas e chocolates — perfeita para compartilhar.",
      "price": 0,
      "categoryId": "cat-especiais",
      "image": "products/719409ec-6dcb-45c2-ad21-adc69e920407.jpg",
      "featured": true,
      "slug": "pizza-brownie",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p9",
      "name": "Bolo de Cenoura com Chocolate",
      "description": "Bolo de cenoura fofinho com cobertura de ganache e raspas de chocolate.",
      "price": 0,
      "categoryId": "cat-bolos",
      "image": "products/8af04d42-db5d-4575-9ee0-ca4d24a9fd99.jpg",
      "featured": false,
      "slug": "bolo-cenoura-chocolate",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p10",
      "name": "Copo Brownie com Morango",
      "description": "Brownie, creme e morangos frescos em camadas — leve e cheio de sabor.",
      "price": 0,
      "categoryId": "cat-copos",
      "image": "products/930630ff-b25d-4a6d-8843-2ef0589851c0.jpg",
      "featured": false,
      "slug": "copo-brownie-morango",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p11",
      "name": "Copo Brownie Gourmet",
      "description": "Copo premium com creme de chocolate, pedaços de brownie e amendoim crocante.",
      "price": 0,
      "categoryId": "cat-copos",
      "image": "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
      "featured": true,
      "slug": "copo-brownie-gourmet",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p12",
      "name": "Pote de Creme Artesanal",
      "description": "Marmitinha com creme pipado em rosetas — ideal para presentear ou saborear no dia a dia.",
      "price": 0,
      "categoryId": "cat-potes",
      "image": "products/b05c8675-2972-47d2-a49d-d2ed4dc93fc6.jpg",
      "featured": false,
      "slug": "pote-creme-artesanal",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p13",
      "name": "Trio de Potinhos",
      "description": "Seleção de três sabores em potinhos — chocolate, morango e cremes artesanais.",
      "price": 0,
      "categoryId": "cat-potes",
      "image": "products/b9fe2ede-b11b-41e1-b819-d29dec7f18f1.jpg",
      "featured": true,
      "slug": "trio-potinhos",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p14",
      "name": "Kit 3 Potinhos",
      "description": "Seleção de três potinhos artesanais com cremes, chocolate e morango — prontos para presentear.",
      "price": 0,
      "categoryId": "cat-potes",
      "image": "products/7288ea2a-8bcc-424b-a2d9-e13d9b0d2cc7.jpg",
      "featured": true,
      "slug": "kit-3-potinhos",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p15",
      "name": "Salgadinho Gourmet",
      "description": "Massa crocante recheada com creme e carne desfiada — opção salgada da Aurora.",
      "price": 0,
      "categoryId": "cat-especiais",
      "image": "products/dcf6f873-6760-4663-a0e4-b5ffb87e0898.jpg",
      "featured": false,
      "slug": "salgadinho-gourmet",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p16",
      "name": "Cookie Recheado Nutella",
      "description": "Cookie grosso com recheio generoso de creme de avelã — puro conforto em cada mordida.",
      "price": 18,
      "categoryId": "cat-cookies",
      "image": "products/6da1f221-d309-46a6-86c6-c55512a40766.jpg",
      "featured": true,
      "slug": "cookie-recheado-nutella",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p17",
      "name": "Bolo no Pote Morango",
      "description": "Camadas de bolo, creme, chocolate e morango fresco — finalizado com morango inteiro.",
      "price": 0,
      "categoryId": "cat-potes",
      "image": "products/ebaf8618-a5e9-4874-9cfd-9d085da4a193.jpg",
      "featured": true,
      "slug": "bolo-no-pote-morango",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p18",
      "name": "Mega brownie",
      "description": "Mega brownie generoso, feito com carinho — perfeito para compartilhar ou saborear sozinho.",
      "price": 38,
      "priceFrom": true,
      "categoryId": "cat-especiais",
      "image": "products/ccae5bfe-0976-4cbb-9484-05c3e75b9695.jpg",
      "featured": true,
      "slug": "mega-brownie",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    }
  ],
  "clients": [],
  "orders": [],
  "reviews": [],
  "faq": [],
  "gallery": [
    "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
    "products/06b9382c-b7eb-422d-bd3a-e7b46b44a936.jpg",
    "products/0ff19f98-37de-4629-9520-af19c38f27cc.jpg",
    "products/27cca0b6-2fd5-4d60-8c72-92a1e8097364.jpg",
    "products/4ba1b56d-f4ea-4b7d-9c2d-2f8fbeab8bb1.jpg",
    "products/4c3b51e1-88fc-473a-a06d-e3f13e31c525.jpg",
    "products/679de717-08f0-4c2d-a601-7bb8bae07bc4.jpg",
    "products/6aceecd0-e407-4478-b511-f03af2e22e65.jpg",
    "products/719409ec-6dcb-45c2-ad21-adc69e920407.jpg",
    "products/8af04d42-db5d-4575-9ee0-ca4d24a9fd99.jpg",
    "products/930630ff-b25d-4a6d-8843-2ef0589851c0.jpg",
    "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg"
  ],
  "finance": []
};
