const AURORA_DEFAULT_DATA = {
  "version": 16,
  "settings": {
    "name": "Aurora Confeitaria Artesanal",
    "tagline": "Feito com amor",
    "logo": "",
    "banner": "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
    "sobreImage": "products/clara-aurora-historia.jpg",
    "whatsapp": "5535987216486",
    "instagram": "https://www.instagram.com/a.aurora.confeitaria",
    "instagramUser": "@a.aurora.confeitaria",
    "facebook": "",
    "email": "contato@aurora.com",
    "address": "Rua dos Expedicionários, 237, Boa Esperança MG, 37170-000, Brasil",
    "hours": "Pedidos pelo WhatsApp",
    "followers": "",
    "posts": "",
    "mapEmbed": "",
    "heroBadge": "Confeitaria artesanal · Boa Esperança/MG",
    "heroStory": [],
    "sobreText1": "A Aurora Confeitaria nasceu do sonho de transformar momentos simples em lembranças especiais. Cada receita é preparada artesanalmente, com ingredientes selecionados, muito carinho e a dedicação de quem acredita que um doce pode tornar o dia de alguém mais feliz.",
    "sobreText2": "Mais do que vender sobremesas, queremos criar experiências. Também acreditamos em fazer a diferença onde estamos — compartilhar o bem faz parte da nossa essência. Seja bem-vindo à Aurora Confeitaria."
  },
  "auth": {
    "email": "auroraconfeitaria2022@gmail.com",
    "password": "aurora123"
  },
  "categories": [
    { "id": "cat-copos", "name": "Copos Brownie", "slug": "copos" },
    { "id": "cat-sandu", "name": "Sandubrownies", "slug": "sandubrownies" },
    { "id": "cat-cookies", "name": "Cookies", "slug": "cookies" },
    { "id": "cat-potes", "name": "Potes", "slug": "potes" },
    { "id": "cat-salgados", "name": "Salgados", "slug": "salgados" },
    { "id": "cat-bolos", "name": "Bolos", "slug": "bolos" },
    { "id": "cat-especiais", "name": "Especiais", "slug": "especiais" }
  ],
  "products": [
    {
      "id": "p0",
      "name": "Copo Brownie da Felicidade",
      "description": "Copo 300ml com camadas generosas de brownie e cremes — promoção especial!",
      "price": 29,
      "categoryId": "cat-copos",
      "image": "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
      "featured": true,
      "slug": "copo-brownie-felicidade",
      "size": "300ml",
      "flavors": [
        "Ninho com Nutella",
        "Morango com Ninho",
        "Brigadeiro com Ninho e Nutella",
        "Brigadeiro com Morango",
        "Brigadeiro com Nutella"
      ],
      "promoActive": true,
      "promoPrice": 22,
      "promoLabel": "Promoção",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-copo-morango",
      "name": "Copo Morango, Ninho e Chocolate",
      "description": "Camadas de morangos frescos, brigadeiro cremoso de leite ninho e ganache de chocolate nobre, com cobertura em Briganache.",
      "price": 29,
      "categoryId": "cat-copos",
      "image": "products/6aceecd0-e407-4478-b511-f03af2e22e65.jpg",
      "featured": true,
      "slug": "copo-morango-ninho-chocolate",
      "size": "300ml",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p-sandu",
      "name": "Sandubrownies",
      "description": "Sanduíche de brownie com recheios especiais. Preço conforme o sabor — ex.: Ninho com Nutella e Morangos R$ 29 (2 por R$ 55).",
      "price": 28,
      "priceFrom": true,
      "categoryId": "cat-sandu",
      "image": "products/4c3b51e1-88fc-473a-a06d-e3f13e31c525.jpg",
      "featured": true,
      "slug": "sandubrownies",
      "size": "",
      "flavors": [
        "Ninho com Nutella",
        "Ninho com Nutella e Morangos",
        "Ferrero",
        "Brigadeiro com Morango e Nutella",
        "Brigadeiro com Nutella"
      ],
      "flavorPrices": {
        "Ninho com Nutella": 28,
        "Ninho com Nutella e Morangos": 29,
        "Ferrero": 34,
        "Brigadeiro com Morango e Nutella": 31,
        "Brigadeiro com Nutella": 28
      },
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-coxinha",
      "name": "Coxinha de Costela com Cream Cheese",
      "description": "Opção salgada do cardápio: coxinha de costela desfiada com cream cheese. Ganha refri 200ml de cortesia.",
      "price": 24.9,
      "categoryId": "cat-salgados",
      "image": "products/dcf6f873-6760-4663-a0e4-b5ffb87e0898.jpg",
      "featured": true,
      "slug": "coxinha-costela-cream-cheese",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-afoga",
      "name": "Afogadinhos",
      "description": "Docinho afogadinho — R$ 13 cada ou 2 por R$ 25.",
      "price": 13,
      "categoryId": "cat-especiais",
      "image": "products/b9fe2ede-b11b-41e1-b819-d29dec7f18f1.jpg",
      "featured": true,
      "slug": "afogadinhos",
      "size": "",
      "flavors": [
        "Kinder",
        "Ninho com Nutella",
        "Ninho com Geleia de Morangos"
      ],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-pudim",
      "name": "Pudim",
      "description": "Pudim cremoso 140ml — R$ 8 cada ou 2 por R$ 15.",
      "price": 8,
      "categoryId": "cat-especiais",
      "image": "products/b05c8675-2972-47d2-a49d-d2ed4dc93fc6.jpg",
      "featured": true,
      "slug": "pudim",
      "size": "140ml",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p-minipote",
      "name": "Mini Bolo de Pote",
      "description": "Mini bolo de pote 140 ml — R$ 8 cada ou 2 por R$ 15. Escolha o sabor.",
      "price": 8,
      "categoryId": "cat-potes",
      "image": "products/7288ea2a-8bcc-424b-a2d9-e13d9b0d2cc7.jpg",
      "featured": true,
      "slug": "mini-bolo-de-pote",
      "size": "140ml",
      "flavors": [
        "Ninho com Nutella",
        "Brigadeiro Maracujá",
        "Ninho com Maracujá",
        "Ninho com Geleia de Morango"
      ],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-cookies",
      "name": "Cookies Premium",
      "description": "Todos no estilo americano: grandes, macios e com recheio generoso. O Tradicional é a massa clássica só com recheio de Nutella.",
      "price": 18,
      "categoryId": "cat-cookies",
      "image": "products/0ff19f98-37de-4629-9520-af19c38f27cc.jpg",
      "featured": true,
      "slug": "cookies-premium",
      "size": "",
      "flavors": [
        "Tradicional (Nutella)",
        "Chocolate",
        "RedVelvet com brigadeiro de cream cheese",
        "Kinder"
      ],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-patinha",
      "name": "Brownie Patinha",
      "description": "Item exclusivo da Aurora criado para apoiar uma ONG de animais da cidade — por isso o nome Patinha. A base é brownie, geralmente com brigadeiro cremoso de ninho e geleia de morango para equilibrar o sabor. Também temos outros sabores!",
      "price": 15,
      "categoryId": "cat-especiais",
      "image": "products/679de717-08f0-4c2d-a601-7bb8bae07bc4.jpg",
      "featured": true,
      "slug": "brownie-patinha",
      "size": "",
      "flavors": [
        "Ninho com Geleia de Morango",
        "Ninho com Nutella",
        "Ferrero",
        "Kinder"
      ],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-torta",
      "name": "Torta Cookies de Nutella",
      "description": "Torta de cookies com Nutella — escolha o sabor do recheio.",
      "price": 23,
      "categoryId": "cat-especiais",
      "image": "products/6da1f221-d309-46a6-86c6-c55512a40766.jpg",
      "featured": true,
      "slug": "torta-cookies-nutella",
      "size": "",
      "flavors": [
        "Ninho com Nutella",
        "Maracujá",
        "Brigadeiro"
      ],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p-recheado",
      "name": "Brownie Recheado",
      "description": "Brownie recheado artesanal embalado com carinho — escolha o sabor (Kinder ou Dois Amores).",
      "price": 15,
      "categoryId": "cat-especiais",
      "image": "products/27cca0b6-2fd5-4d60-8c72-92a1e8097364.jpg",
      "featured": true,
      "slug": "brownie-recheado",
      "size": "",
      "flavors": [
        "Kinder",
        "Dois Amores"
      ],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p18",
      "name": "Mega brownie",
      "description": "Mega brownie generoso com brigadeiro cremoso de leite ninho, ganache de chocolate e morangos frescos — perfeito para compartilhar.",
      "price": 38,
      "priceFrom": true,
      "categoryId": "cat-especiais",
      "image": "products/ccae5bfe-0976-4cbb-9484-05c3e75b9695.jpg",
      "featured": true,
      "slug": "mega-brownie",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    }
  ],
  "clients": [],
  "orders": [],
  "reviews": [],
  "faq": [],
  "gallery": [
    "products/9dae6d0f-4354-459a-aa17-50081e3f0afb.jpg",
    "products/06b9382c-b7eb-422d-bd3a-e7b46b44a936.jpg",
    "products/0ff19f98-37de-4629-9520-af19c38f27cc.jpg",
    "products/27cca0b6-2fd5-4d60-8c72-92a1e8097364.jpg",
    "products/4ba1b56d-f4ea-4b7d-9c2d-2f8fbeab8bb1.jpg",
    "products/4c3b51e1-88fc-473a-a06d-e3f13e31c525.jpg",
    "products/6da1f221-d309-46a6-86c6-c55512a40766.jpg",
    "products/ccae5bfe-0976-4cbb-9484-05c3e75b9695.jpg",
    "products/ebaf8618-a5e9-4874-9cfd-9d085da4a193.jpg",
    "products/dcf6f873-6760-4663-a0e4-b5ffb87e0898.jpg"
  ],
  "finance": []
};
